### ISSUE TITLE
Modifying SCF parameters

### ISSUE THREAD

**Issue by rudrab** [ase2sprkkr/ase2sprkkr#2]
Dear Developers,
I am trying to modify the input parameters as:
```
print(structure.get_cell()[0, 0])
input_parameters = InputParameters.create("SCF")
#  input_parameters.ENERGY.GRID = 5
input_parameters.SCF.VXC = "PBE"
input_parameters.SCF.ALG = "BROYDEN2"  (as it comes with `scfalg` in `xband`)

```
But I am getting error like:
`ValueError: Value 'PBE' for paramater VXC of type FixedValue(VWN) is not valid: Required one of [VWN]
`
or
`AttributeError: No ALG member of <ase2sprkkr.input_parameters.input_parameters_definitions.SectionDefinition object at 0x7f9438b708d0>
`
I am trying to define the customization in `input_parameters` before the calculator is set.  
Is this possible?

**Comment by lokik** [comment]
Dear Rudrab,
please try beta version 2.0.0b1. There are (beside others) two changes that should solve the issue:
- first, the definition of the tasks have been improved to cover all the options mentioned in SPRKKR manual (and some undocumented), so the VXC and ALG options should now accept the mentioned values
- second, there is a new metod: Option.set_dangerous, that allows to set a given option to any value you desire (for the case when the definition would still do not cover all the SPRKKR options)
I hope that it helps,
Sincerelly, Matyas Novak

PS:  The version is available on the pip using 
pip install --pre --upgrade  ase2sprkkr
if you need anaconda release, please let me know
